### ISSUE TITLE
Hello I8Beef

### ISSUE THREAD

**Issue by kdubious** [i8beef/I8Beef.ACInfinity#1]
Hello, wondering what your plans are for this library, @i8beef. Might be worth a quick chat?

**Comment by i8beef** [comment]
I was implementing this in order to create a bridge between AC Infinity's APIs and MQTT for my home automation system (ie, USE this library in another project). I got it far enough that I could connect and query the status, but stopped there as the utility wasn't there for me once I saw what I could get...

CONTROL through their API could let you turn things on / off, etc., but I don't run my system like that and suspect most others don't either: I setup my tent with "Advanced Automation" and I think either (a) controls do NOTHING in that mode, or worse, (b) put the controller in an unsupported state where I was able to directly control things that the app explicitly doesn't allow when in Advanced Automation mode... I didn't get far enough to figure out what the implications were for that.

For STATUS I could get all that, so you could spit out what was currently active, etc. The API has some weird naming conventions which I think I was just spitting out as is, but frankly its hard to tell what anything is because its all called weird stuff... I also think I had some questions about if the status was ACCURATE when Advanced mode, like it only reflected the underlying MANUAL setting, but not the actual CURRENT status or something weird, but I forget the details.

In the end I was going to basically do a bunch of work to spit out like 4 booleans and a couple of numbers for temp / humidity / vpd for device status, and lost a little interest. I haven't come back to it yet.

**Comment by kdubious** [comment]
My use case was going to be more along the lines of trying to connect the dots between the historical data from the tent with any / all additional data you could get your hands on. Daily weights, watering details, nutrient / feeds, PPFD, etc.

That JSON object you parse from them does have some strangely named properties, like "speak"? Yikes.

**Comment by i8beef** [comment]
Yeah I never figured out how to get historical readings, etc. I couldn't even tell what the things I WAS getting actually were because of the weird names. I figured I'd need to map it out, and thats about when I put it down.

**Comment by kdubious** [comment]
Cool, well thanks for your time, and for leaving the breadcrumbs behind!
